### ISSUE TITLE
Enable https for interfaces and services

### ISSUE THREAD

**Issue by c-w** [CatalystCode/fortisdeploy#243]
Currently the React frontend and the GraphQL backend communicate via HTTP. Payloads may contain secrets (e.g. Cognitive Service or Facebook or Twitter credentials) so we should have this via HTTPS.

Spun out from https://github.com/CatalystCode/project-fortis-pipeline/issues/175.

**Comment by c-w** [comment]
Note that in the project-fortis-mono repo, the project-fortis-interfaces is served via blob storage which already has https, so we'd only need to add a certificate to the NodeJS GraphQL service running in kubernetes and we'd be done.

**Comment by c-w** [comment]
Input from @timfpark below:

---

I do the following - I create an NGINX ingress controller via:
`helm install stable/nginx-ingress --name nginx-ingress --namespace nginx-ingress --set controller.replicaCount=3`
then create a secret for the TLS ala:
`kubectl create secret tls mydomain-tls-secret --key ../../ssl/wildcard.mydomain.io.key --cert ../../ssl/wildcard.mydomain.io-bundle.crt --namespace $SERVICE_NAME`
then you need to create an Ingress for your application that specifies the host name and references this secret:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ .Values.serviceName }}-ingress
  namespace: {{ .Values.serviceName }}
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.serviceName }}
              servicePort: {{ .Values.servicePort }}
            path: /
  tls:
      - hosts:
          - {{ .Values.hostname }}
        secretName: {{ .Values.tlsSecretName }}
```
 
I do all of this in a set of general scripts that you can see here in case they are helpful.  Check out apps/simple-service and trace the bash script to see how it all works.   The NGINX ingress controller is all set up in create-cluster.
 
https://github.com/timfpark/azure-k8s-devops

---

**Comment by c-w** [comment]
Via Alessandro Vozza:

---

or use Let's encrypt certificates via kube-lego: https://github.com/kubernetes/charts/tree/master/stable/kube-lego (it auto-renews the certificates as well). You can then enable it on a per-ingress basis:

```
metadata:
  name: hello-world
  annotations:
    # enable kube-lego for this ingress
    kubernetes.io/tls-acme: "true"
```

---
